server:
  port: 8080

spring:
  application:
    name: pix-example
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:pixdb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect